### ISSUE TITLE
Change apt back to old method

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/iot-lora-gateway#15]
https://github.com/PiSupply/iot-lora-gateway/blob/6f07f425c8a894654268618170a50d02d1489f64/iot-lora-installer#L78
Installing each package separately takes much longer. (Noticeable 1-2 minutes on older Raspberry Pi Models).

**Comment by robputt796** [comment]
Seems fair, in this case we should concatenate the list rather than having a PEP8 defying string.
